=== shashikantmhatre/RnD/SIMRatingDataImport/src/main/resources/com/mmpnc/rating/algorithm/configuration/Configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<xsd:element name="Configuration">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="IgnorePCH" type="Programs" minOccurs="1"
					maxOccurs="1" />
				<xsd:element name="ProgramPCH" type="Programs" minOccurs="1"
					maxOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="Programs">
		<xsd:sequence>
			<xsd:element name="Program" type="xsd:string" minOccurs="1"
				maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== shashikantmhatre/RnD/SIMRatingDataImport/src/main/resources/com/mmpnc/rating/algorithm/configuration/Configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Configuration.xsd">
  <IgnorePCH>
    <Program>integerAmount</Program>
    <Program>deductibleAmount</Program>
    <Program>domainTableLookup</Program>
    <Program>domainZipCodeTableLookup</Program>
    <Program>domainCountyTableLookup</Program>
  	<!-- 
    <Program>BusnPrsnPropLimitOfInsRelativityFactor</Program>
  	 -->
  </IgnorePCH>
  <ProgramPCH>
    <Program>GetDeductible</Program>
    <Program>Lookup.*\{.*</Program>
  </ProgramPCH>
</Configuration>
