=== shashikantmhatre/RnD/SIMRater/src/main/resources/com/mmpnc/rating/ProductSchema.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="DomainTable">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Id" type="xs:ID" minOccurs="0"/>
        <xs:element name="Name" type="xs:string" minOccurs="0"/>
        <xs:element name="Title" type="xs:string" minOccurs="0"/>
        <xs:element name="Type" type="xs:string" minOccurs="0"/>
        <xs:element name="Overridden" type="xs:boolean"/>
        <xs:element name="BureauRuleNumber" type="xs:string" minOccurs="0"/>
        <!-- 
        <xs:element ref="Product" minOccurs="0"/>
         -->
		<xs:element name="Product" type="xs:IDREF" minOccurs="0"/>
        <xs:element ref="DomainTable" minOccurs="0"/>
        <xs:element ref="DomainTableConfiguration" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="DomainTableEntry" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="DomainTableConfiguration">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Id" type="xs:ID" minOccurs="0"/>
        <xs:element name="ConfigurationType" type="xs:string" minOccurs="0"/>
        <xs:element name="Sequence" type="xs:int"/>
        <xs:element name="Name" type="xs:string" minOccurs="0"/>
        <xs:element name="LookupType" type="xs:string" minOccurs="0"/>
        <xs:element name="Type" type="xs:string" minOccurs="0"/>
        <xs:element name="Description" type="xs:string" minOccurs="0"/>
        <xs:element name="size" type="xs:int"/>
        <xs:element name="Scale" type="xs:int"/>
        <!-- 
        
        <xs:element ref="Product" minOccurs="0"/>
        <xs:element ref="DomainTable" minOccurs="0"/>
         -->
		<xs:element name="Product" type="xs:IDREF" minOccurs="0"/>
		<xs:element name="DomainTable" type="xs:IDREF" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="DomainTableEntry">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Id" type="xs:ID" minOccurs="0"/>
        <xs:element name="Sequence" type="xs:int"/>
        <xs:element name="Status" type="xs:string" minOccurs="0"/>
        <!-- 
        <xs:element ref="DomainTable" minOccurs="0"/>
        <xs:element ref="Product" minOccurs="0"/>
         -->
		<xs:element name="Product" type="xs:IDREF" minOccurs="0"/>
		<xs:element name="DomainTable" type="xs:IDREF" minOccurs="0"/>
        <xs:element name="Column1" type="xs:string" minOccurs="0"/>
        <xs:element name="Column2" type="xs:string" minOccurs="0"/>
        <xs:element name="Column3" type="xs:string" minOccurs="0"/>
        <xs:element name="Column4" type="xs:string" minOccurs="0"/>
        <xs:element name="Column5" type="xs:string" minOccurs="0"/>
        <xs:element name="Column6" type="xs:string" minOccurs="0"/>
        <xs:element name="Column7" type="xs:string" minOccurs="0"/>
        <xs:element name="Column8" type="xs:string" minOccurs="0"/>
        <xs:element name="Column9" type="xs:string" minOccurs="0"/>
        <xs:element name="Column10" type="xs:string" minOccurs="0"/>
        <xs:element name="NColumn1" type="xs:double" minOccurs="0"/>
        <xs:element name="NColumn2" type="xs:double" minOccurs="0"/>
        <xs:element name="NColumn3" type="xs:double" minOccurs="0"/>
        <xs:element name="NColumn4" type="xs:double" minOccurs="0"/>
        <xs:element name="NColumn5" type="xs:double" minOccurs="0"/>
        <xs:element name="NColumn6" type="xs:double" minOccurs="0"/>
        <xs:element name="NColumn7" type="xs:double" minOccurs="0"/>
        <xs:element name="NColumn8" type="xs:double" minOccurs="0"/>
        <xs:element name="NColumn9" type="xs:double" minOccurs="0"/>
        <xs:element name="NColumn10" type="xs:double" minOccurs="0"/>
        <xs:element name="Code" type="xs:string" minOccurs="0"/>
        <xs:element name="Description" type="xs:string" minOccurs="0"/>
        <xs:element name="MinValue" type="xs:double" minOccurs="0"/>
        <xs:element name="MaxValue" type="xs:double" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Product">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Id" type="xs:ID" minOccurs="0"/>
        <xs:element name="LOB" type="xs:string" minOccurs="0"/>
        <xs:element name="Program" type="xs:string" minOccurs="0"/>
        <xs:element name="State" type="xs:string" minOccurs="0"/>
        <xs:element name="Title" type="xs:string" minOccurs="0"/>
        <xs:element name="NewBusinessEffectiveDate" type="xs:dateTime" minOccurs="0"/>
        <xs:element name="NewBusinessExpirationDate" type="xs:dateTime" minOccurs="0"/>
        <xs:element name="RenewalEffectiveDate" type="xs:dateTime" minOccurs="0"/>
        <xs:element name="RenewalExpirationDate" type="xs:dateTime" minOccurs="0"/>
        <xs:element ref="Product" minOccurs="0"/>
        <xs:element ref="RateTable" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="DomainTable" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="RatingEntity" type="RatingEntity" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="RateTable" type="RateTable"/>

  <xs:element name="RateTableConfiguration">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Id" type="xs:ID" minOccurs="0"/>
        <xs:element name="ConfigurationType" type="xs:string" minOccurs="0"/>
        <xs:element name="Sequence" type="xs:int"/>
        <xs:element name="Name" type="xs:string" minOccurs="0"/>
        <xs:element name="LookupType" type="xs:string" minOccurs="0"/>
        <xs:element name="Type" type="xs:string" minOccurs="0"/>
        <xs:element name="Description" type="xs:string" minOccurs="0"/>
        <xs:element name="Size" type="xs:int"/>
        <xs:element name="Scale" type="xs:int"/>
        <!-- 
        <xs:element ref="Product" minOccurs="0"/>
        <xs:element ref="RateTable" minOccurs="0"/>
         -->
		<xs:element name="Product" type="xs:IDREF" minOccurs="0"/>
		<xs:element name="RateTable" type="xs:IDREF" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="RateTableEntry">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Id" type="xs:ID" minOccurs="0"/>
        <xs:element name="Sequence" type="xs:int"/>
        <xs:element name="Status" type="xs:string" minOccurs="0"/>
        <!-- 
        <xs:element ref="RateTable" minOccurs="0"/>
        <xs:element ref="Product" minOccurs="0"/>
         -->
		<xs:element name="Product" type="xs:IDREF" minOccurs="0"/>
		<xs:element name="RateTable" type="xs:IDREF" minOccurs="0"/>
        <xs:element name="Column1" type="xs:string" minOccurs="0"/>
        <xs:element name="Column2" type="xs:string" minOccurs="0"/>
        <xs:element name="Column3" type="xs:string" minOccurs="0"/>
        <xs:element name="Column4" type="xs:string" minOccurs="0"/>
        <xs:element name="Column5" type="xs:string" minOccurs="0"/>
        <xs:element name="Column6" type="xs:string" minOccurs="0"/>
        <xs:element name="Column7" type="xs:string" minOccurs="0"/>
        <xs:element name="Column8" type="xs:string" minOccurs="0"/>
        <xs:element name="Column9" type="xs:string" minOccurs="0"/>
        <xs:element name="Column10" type="xs:string" minOccurs="0"/>
        <xs:element name="NColumn1" type="xs:double" minOccurs="0"/>
        <xs:element name="NColumn2" type="xs:double" minOccurs="0"/>
        <xs:element name="NColumn3" type="xs:double" minOccurs="0"/>
        <xs:element name="NColumn4" type="xs:double" minOccurs="0"/>
        <xs:element name="NColumn5" type="xs:double" minOccurs="0"/>
        <xs:element name="NColumn6" type="xs:double" minOccurs="0"/>
        <xs:element name="NColumn7" type="xs:double" minOccurs="0"/>
        <xs:element name="NColumn8" type="xs:double" minOccurs="0"/>
        <xs:element name="NColumn9" type="xs:double" minOccurs="0"/>
        <xs:element name="NColumn10" type="xs:double" minOccurs="0"/>
        <xs:element name="ReturnValue" type="xs:string" minOccurs="0"/>
        <xs:element name="ReturnNValue" type="xs:double" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="RateTable">
    <xs:sequence>
      <xs:element name="Id" type="xs:ID" minOccurs="0"/>
      <xs:element name="Name" type="xs:string" minOccurs="0"/>
      <xs:element name="Title" type="xs:string" minOccurs="0"/>
      <xs:element name="Overridden" type="xs:boolean"/>
      <xs:element name="BureauRuleNumber" type="xs:string" minOccurs="0"/>
      <!-- 
      <xs:element ref="Product" minOccurs="0"/>
      <xs:element ref="RateTable" minOccurs="0"/>
       -->	
	  <xs:element name="Product" type="xs:IDREF" minOccurs="0"/>
	  <xs:element name="RateTable" type="xs:IDREF" minOccurs="0"/>
      <xs:element ref="RateTableConfiguration" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element ref="RateTableEntry" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="RatingEntity">
    <xs:sequence>
      <xs:element name="Id" type="xs:ID" minOccurs="0"/>
      <xs:element name="Name" type="xs:string" minOccurs="0"/>
      <!-- 
      <xs:element ref="Product" minOccurs="0"/>
       -->
	  <xs:element name="Product" type="xs:IDREF" minOccurs="0"/> 	
      <xs:element name="RatingProcess" type="RatingProcess" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="RatingProcess">
    <xs:sequence>
      <xs:element name="Id" type="xs:ID" minOccurs="0"/>
      <xs:element name="Name" type="xs:string" minOccurs="0"/>
      <xs:element name="RatingEntity" type="xs:IDREF" minOccurs="0"/>
      <xs:element name="ExecutionOrder" type="xs:int"/>
      <!-- 
      <xs:element ref="Product" minOccurs="0"/>
       -->
	  <xs:element name="Product" type="xs:IDREF" minOccurs="0"/>
      <xs:element name="ProcessStep" type="RatingStep" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="RatingProgram" type="RatingProgram" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="RatingStep">
    <xs:sequence>
      <xs:element name="Id" type="xs:ID" minOccurs="0"/>
      <xs:element name="ExecutionOrder" type="xs:int"/>
      <xs:element name="Block" type="xs:string" minOccurs="0"/>
      <xs:element name="Product" type="xs:IDREF" minOccurs="0"/>
      <xs:element name="RatingProcess" type="xs:IDREF" minOccurs="0"/>
      <xs:element name="RatingProgram" type="xs:IDREF" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="RatingProgram">
    <xs:sequence>
      <xs:element name="Id" type="xs:ID" minOccurs="0"/>
      <xs:element name="Name" type="xs:string" minOccurs="0"/>
      <xs:element name="ExecutionOrder" type="xs:int"/>
      <xs:element name="Product" type="xs:IDREF" minOccurs="0"/>
      <xs:element name="RatingProcess" type="xs:IDREF" minOccurs="0"/>
      <xs:element name="ProgramStep" type="RatingStep" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="valueConfiguration">
    <xs:sequence>
      <xs:element name="maxValue" type="xs:double"/>
      <xs:element name="minValue" type="xs:double"/>
      <xs:element name="name" type="xs:string" minOccurs="0"/>
      <xs:element name="value" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="dataValue">
    <xs:sequence>
      <xs:element name="key" type="xs:string" minOccurs="0"/>
      <xs:element name="value" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="uuidGenerator">
    <xs:sequence/>
  </xs:complexType>

  <xs:complexType name="keyConfiguration">
    <xs:sequence>
      <xs:element name="name" type="xs:string" minOccurs="0"/>
      <xs:element name="value" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== shashikantmhatre/RnD/SIMRater/src/main/resources/com/mmpnc/rating/ProductSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<Product xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ProductSchema.xsd">
  <Id>idvalue0</Id>
  <LOB>LOB</LOB>
  <Program>Program</Program>
  <State>State</State>
  <Title>Title</Title>
  <NewBusinessEffectiveDate>2001-12-31T12:00:00</NewBusinessEffectiveDate>
  <NewBusinessExpirationDate>2001-12-31T12:00:00</NewBusinessExpirationDate>
  <RenewalEffectiveDate>2001-12-31T12:00:00</RenewalEffectiveDate>
  <RenewalExpirationDate>2001-12-31T12:00:00</RenewalExpirationDate>
  <RateTable>
    <Id>idvalue1</Id>
    <Name>Name</Name>
    <Title>Title</Title>
    <Overridden>true</Overridden>
    <BureauRuleNumber>BureauRuleNumber</BureauRuleNumber>
    <RateTableConfiguration>
      <Id>idvalue2</Id>
      <ConfigurationType>ConfigurationType</ConfigurationType>
      <Sequence>0</Sequence>
      <Name>Name</Name>
      <LookupType>LookupType</LookupType>
      <Type>Type</Type>
      <Description>Description</Description>
      <Size>0</Size>
      <Scale>0</Scale>
    </RateTableConfiguration>
    <RateTableEntry>
      <Id>idvalue3</Id>
      <Sequence>0</Sequence>
      <Status>Status</Status>
      <Column1>Column1</Column1>
      <Column2>Column2</Column2>
      <Column3>Column3</Column3>
      <Column4>Column4</Column4>
      <Column5>Column5</Column5>
      <Column6>Column6</Column6>
      <Column7>Column7</Column7>
      <Column8>Column8</Column8>
      <Column9>Column9</Column9>
      <Column10>Column10</Column10>
      <NColumn1>0.0</NColumn1>
      <NColumn2>0.0</NColumn2>
      <NColumn3>0.0</NColumn3>
      <NColumn4>0.0</NColumn4>
      <NColumn5>0.0</NColumn5>
      <NColumn6>0.0</NColumn6>
      <NColumn7>0.0</NColumn7>
      <NColumn8>0.0</NColumn8>
      <NColumn9>0.0</NColumn9>
      <NColumn10>0.0</NColumn10>
      <ReturnValue>ReturnValue</ReturnValue>
      <ReturnNValue>0.0</ReturnNValue>
    </RateTableEntry>
  </RateTable>
  <DomainTable>
    <Id>idvalue4</Id>
    <Name>Name</Name>
    <Title>Title</Title>
    <Type>Type</Type>
    <Overridden>true</Overridden>
    <BureauRuleNumber>BureauRuleNumber</BureauRuleNumber>
    <DomainTableConfiguration>
      <Id>idvalue5</Id>
      <ConfigurationType>ConfigurationType</ConfigurationType>
      <Sequence>0</Sequence>
      <Name>Name</Name>
      <LookupType>LookupType</LookupType>
      <Type>Type</Type>
      <Description>Description</Description>
      <size>0</size>
      <Scale>0</Scale>
    </DomainTableConfiguration>
    <DomainTableEntry>
      <Id>idvalue6</Id>
      <Sequence>0</Sequence>
      <Status>Status</Status>
      <Column1>Column1</Column1>
      <Column2>Column2</Column2>
      <Column3>Column3</Column3>
      <Column4>Column4</Column4>
      <Column5>Column5</Column5>
      <Column6>Column6</Column6>
      <Column7>Column7</Column7>
      <Column8>Column8</Column8>
      <Column9>Column9</Column9>
      <Column10>Column10</Column10>
      <NColumn1>0.0</NColumn1>
      <NColumn2>0.0</NColumn2>
      <NColumn3>0.0</NColumn3>
      <NColumn4>0.0</NColumn4>
      <NColumn5>0.0</NColumn5>
      <NColumn6>0.0</NColumn6>
      <NColumn7>0.0</NColumn7>
      <NColumn8>0.0</NColumn8>
      <NColumn9>0.0</NColumn9>
      <NColumn10>0.0</NColumn10>
      <Code>Code</Code>
      <Description>Description</Description>
      <MinValue>0.0</MinValue>
      <MaxValue>0.0</MaxValue>
    </DomainTableEntry>
  </DomainTable>
  <RatingEntity>
    <Id>idvalue7</Id>
    <Name>Name</Name>
    <Product>idvalue0</Product>
    <RatingProcess>
      <Id>idvalue8</Id>
      <Name>Name</Name>
      <RatingEntity>idvalue0</RatingEntity>
      <ExecutionOrder>0</ExecutionOrder>
      <Product>idvalue0</Product>
      <ProcessStep>
        <Id>idvalue9</Id>
        <ExecutionOrder>0</ExecutionOrder>
        <Block>Block</Block>
        <Product>idvalue0</Product>
        <RatingProcess>idvalue0</RatingProcess>
        <RatingProgram>idvalue0</RatingProgram>
      </ProcessStep>
      <RatingProgram>
        <Id>idvalue10</Id>
        <Name>Name</Name>
        <ExecutionOrder>0</ExecutionOrder>
        <Product>idvalue0</Product>
        <RatingProcess>idvalue0</RatingProcess>
        <ProgramStep>
          <Id>idvalue11</Id>
          <ExecutionOrder>0</ExecutionOrder>
          <Block>Block</Block>
          <Product>idvalue0</Product>
          <RatingProcess>idvalue0</RatingProcess>
          <RatingProgram>idvalue0</RatingProgram>
        </ProgramStep>
      </RatingProgram>
    </RatingProcess>
  </RatingEntity>
</Product>
